# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/nicolas/.local/share/QGIS/QGIS3/profiles/default/python/plugins/relief_fill/relief_fill_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ReliefFillDialogBase(object):
    def setupUi(self, ReliefFillDialogBase):
        ReliefFillDialogBase.setObjectName("ReliefFillDialogBase")
        ReliefFillDialogBase.resize(400, 351)
        self.button_box = QtWidgets.QDialogButtonBox(ReliefFillDialogBase)
        self.button_box.setGeometry(QtCore.QRect(30, 310, 341, 32))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.menu_direction = QtWidgets.QComboBox(ReliefFillDialogBase)
        self.menu_direction.setGeometry(QtCore.QRect(20, 210, 171, 25))
        self.menu_direction.setObjectName("menu_direction")
        self.menu_direction.addItem("")
        self.menu_direction.addItem("")
        self.menu_relief = QtWidgets.QComboBox(ReliefFillDialogBase)
        self.menu_relief.setGeometry(QtCore.QRect(20, 150, 171, 25))
        self.menu_relief.setObjectName("menu_relief")
        self.menu_relief.addItem("")
        self.menu_relief.addItem("")
        self.label = QtWidgets.QLabel(ReliefFillDialogBase)
        self.label.setGeometry(QtCore.QRect(20, 10, 151, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(ReliefFillDialogBase)
        self.label_2.setGeometry(QtCore.QRect(20, 250, 121, 17))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(ReliefFillDialogBase)
        self.label_3.setGeometry(QtCore.QRect(20, 130, 191, 17))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(ReliefFillDialogBase)
        self.label_4.setGeometry(QtCore.QRect(20, 190, 171, 20))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(ReliefFillDialogBase)
        self.label_5.setGeometry(QtCore.QRect(20, 70, 171, 17))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(ReliefFillDialogBase)
        self.label_6.setGeometry(QtCore.QRect(200, 70, 171, 17))
        self.label_6.setObjectName("label_6")
        self.input_pt_x = QtWidgets.QLineEdit(ReliefFillDialogBase)
        self.input_pt_x.setGeometry(QtCore.QRect(20, 90, 171, 25))
        self.input_pt_x.setObjectName("input_pt_x")
        self.input_pt_y = QtWidgets.QLineEdit(ReliefFillDialogBase)
        self.input_pt_y.setGeometry(QtCore.QRect(200, 90, 171, 25))
        self.input_pt_y.setObjectName("input_pt_y")
        self.layoutWidget = QtWidgets.QWidget(ReliefFillDialogBase)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 270, 351, 27))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.output_txt = QtWidgets.QLineEdit(self.layoutWidget)
        self.output_txt.setObjectName("output_txt")
        self.horizontalLayout.addWidget(self.output_txt)
        self.output_browse = QtWidgets.QPushButton(self.layoutWidget)
        self.output_browse.setMinimumSize(QtCore.QSize(80, 0))
        self.output_browse.setObjectName("output_browse")
        self.horizontalLayout.addWidget(self.output_browse)
        self.layoutWidget1 = QtWidgets.QWidget(ReliefFillDialogBase)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 30, 351, 27))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.input_dem_txt = QtWidgets.QLineEdit(self.layoutWidget1)
        self.input_dem_txt.setObjectName("input_dem_txt")
        self.horizontalLayout_2.addWidget(self.input_dem_txt)
        self.input_dem_browse = QtWidgets.QPushButton(self.layoutWidget1)
        self.input_dem_browse.setMinimumSize(QtCore.QSize(80, 0))
        self.input_dem_browse.setObjectName("input_dem_browse")
        self.horizontalLayout_2.addWidget(self.input_dem_browse)

        self.retranslateUi(ReliefFillDialogBase)
        self.button_box.accepted.connect(ReliefFillDialogBase.accept)
        self.button_box.rejected.connect(ReliefFillDialogBase.reject)
        QtCore.QMetaObject.connectSlotsByName(ReliefFillDialogBase)

    def retranslateUi(self, ReliefFillDialogBase):
        _translate = QtCore.QCoreApplication.translate
        ReliefFillDialogBase.setWindowTitle(_translate("ReliefFillDialogBase", "Relief Fill"))
        self.menu_direction.setItemText(0, _translate("ReliefFillDialogBase", "upstream"))
        self.menu_direction.setItemText(1, _translate("ReliefFillDialogBase", "downstream"))
        self.menu_relief.setItemText(0, _translate("ReliefFillDialogBase", "altitude"))
        self.menu_relief.setItemText(1, _translate("ReliefFillDialogBase", "drainage basin"))
        self.label.setText(_translate("ReliefFillDialogBase", "Input DEM layer"))
        self.label_2.setText(_translate("ReliefFillDialogBase", "Output fill layer"))
        self.label_3.setText(_translate("ReliefFillDialogBase", "Relief property to extract"))
        self.label_4.setText(_translate("ReliefFillDialogBase", "Direction from the point"))
        self.label_5.setText(_translate("ReliefFillDialogBase", "Input point X coord."))
        self.label_6.setText(_translate("ReliefFillDialogBase", "Input point Y coord."))
        self.output_browse.setText(_translate("ReliefFillDialogBase", "..."))
        self.input_dem_browse.setText(_translate("ReliefFillDialogBase", "..."))
